### ISSUE TITLE
Natural sort doesn't work with contextual filters

### ISSUE THREAD

**Issue by leeksoup** [backdrop-contrib/views_natural_sort#3]
Separate issue for contextual filtering, as promised. :)

I allow the first letter to be passed to the View as a contextual filter, and the books beginning with "A ..." don't show up in the pages under the appropriate letters, unless the second word also begins with "A". E.g. "An American Alphabet" does appear on the "A" page, but "A Boy and His Pony" doesn't show up on the "B" page, though it should. Instead it shows up on the "A" page. 

In other words, contextual filters don't work.

It appears that they are also broken in the latest D7 version, although they used to work a few years ago. Please see this comment in the Drupal issue queue: https://www.drupal.org/project/views_natural_sort/issues/2832868#comment-13619204
> concerning the D7 ticket for glossary support, that is actually already possible. What I did in D7, was use the field Node: Title - Natural and exclude from display, and use that field as a contextual filter. Works perfectly.

More comments at #2

**Comment by keiserjb** [comment]
From the comments in Drupal, I do not believe this ever worked as a feature of the module itself.  It is not part of the D7 or D8+ version.  If there is a solution over there, perhaps I can Backport it.  This would not block a release if I decided to put it in Backdrop contrib.

**Comment by keiserjb** [comment]
If you can figure out how to do that, "What I did in D7, was use the field Node: Title - Natural and exclude from display, and use that field as a contextual filter," please let me know.  I spent this morning on it and could not figure it out.

**Comment by leeksoup** [comment]
Well, I know it worked because I used it on my site. 

Thanks for looking into it. I will try to figure it out and let you know if I am successful.

**Comment by keiserjb** [comment]
If you have this working in D7 could you screenshot the view configuration?

**Comment by keiserjb** [comment]
It is actually quite possible that if this works in D7 that it's something with Views itself.  I am not sure the Views in Backdrop core has kept up with the Views in D7 contrib.

**Comment by leeksoup** [comment]
Well, it doesn't work in D7 any more, sadly. The only clue I can offer is that there used to be a Contextual Filter on Content: Title - Natural (or something similar) but that is now gone. Of course if I match against the normal node title field it will fail exactly as I reported.

Until this can be added, maybe you should just note in the README that contextual filters don't work?

**Comment by leeksoup** [comment]
Do you have any experience with writing Views plugins? One of the Drupal links you posted mentioned that as a way to make the glossary-type sort work.

**Comment by keiserjb** [comment]
No experience with the views plugin.  Contextual filters do not work in either the D7 or D8 module.  I would encourage you to comment on the issues in the Drupal queue.

**Comment by keiserjb** [comment]
When I install the 1.4 release of Views Natural Sort from 2012 I get the field.  That hasn't been a part of the module in a very, very long time.  I can only surmise that the approach did not work as well and that is why it was abandoned so long ago.  

![image](https://user-images.githubusercontent.com/41843284/226221786-7c101ec9-ce9b-459f-b50c-6e57bec98641.png)

**Comment by leeksoup** [comment]
Thanks for chasing that down! It worked very well -- I have no idea why they removed it.

I can try posting over at Drupal, but I don't think any further development is happening on D7 in any case. Hence the whole purpose of the Backdrop fork. :)

**Comment by keiserjb** [comment]
If you really want that field back you could just download the 1.4 version of the module and run it through the coder upgrade module.  It would probably work, but I don't think that is the direction that the official port should take.

**Comment by leeksoup** [comment]
Hmm, maybe I could compare and see the code that got removed ... or maybe not. It looks like the working contextual filter feature went away when they added the ability to natural sort on Fields in the 2.x branch, which involved a big code reorg.

Makes sense about the port.

**Comment by leeksoup** [comment]
I'm looking at the 1.4 version of the module and I can't figure out how it worked. The views_natural_sort.inc file defines the functions to remove the unwanted beginning words etc but they don't appear to actually be called anywhere in the module. 

```
$ grep -iR views_natural_sort_remove_ .
./views_natural_sort.inc:function views_natural_sort_remove_beginning_words($string) {
./views_natural_sort.inc:function views_natural_sort_remove_words($string) {
./views_natural_sort.inc:function views_natural_sort_remove_symbols($string) {
```
I mean, they _must_ be called somehow, but I don't see where / how.

In the current version, these functions are called from the .module file, as I would expect.
```
$ grep -iR views_natural_sort_remove_ .
./views_natural_sort.inc:function views_natural_sort_remove_beginning_words($string) {
./views_natural_sort.inc:function views_natural_sort_remove_words($string) {
./views_natural_sort.inc:function views_natural_sort_remove_symbols($string) {
./views_natural_sort.module:    'views_natural_sort_remove_beginning_words',
./views_natural_sort.module:    'views_natural_sort_remove_words',
./views_natural_sort.module:    'views_natural_sort_remove_symbols',
./views_natural_sort.test:      $this->assertEqual(views_natural_sort_remove_symbols($title), $expected[$key]);

```

I also don't see anything that obviously creates the "Node: Title - Natural" contextual filter but will keep looking.

**Comment by leeksoup** [comment]
I tried comparing the code for that version with the current one. There are major changes throughout and I couldn't figure out what was the relevant part for the Node: Title - Natural field.

**Comment by keiserjb** [comment]
It's is very different and this feature request is going to work very differently but you have the option of taking the other route.

**Comment by leeksoup** [comment]
I was able to work around this problem by defining a Computed Field to hold the "natural sort" version of the title. Obviously, this isn't a great solution since it involves calculating and storing the same info a second time.

**Comment by argiepiano** [comment]
> I allow the first letter to be passed to the View as a contextual filter

How do you filter by the first letter by passing a single letter in the contextual filter?

**Comment by keiserjb** [comment]
@argiepiano That doesn't work with the current version of the module.  It worked in an old version and went away over in Drupal.  It's something to try and fix.

I'm interested in how the computed field worked @leeksoup.

**Comment by argiepiano** [comment]
@keiserjb my question was how, REGARDLESS of whether you used this module, @leeksoup was able to filter nodes by the first letter of the title. I found the answer after digging a while: you can do that by adding Title as contextual filter, and then going to "More" in the contextual filter configuration, and selecting "Glossary mode". I didn't know about that functionality.

And yes, I'm able to confirm that doing this will not use the natural sorting, but rather will display the title "A book with a voice" if you filter by "A" in the URL.

**Comment by leeksoup** [comment]
@argiepiano, correct. I set up the code for the Computed Field to something similar to what the natural sort module does, and then enabled the Glossary mode as you noted in #issuecomment-1518196691

Here's my code, as entered in the Computed Field config. 
```
$title = $entity->title;
$sortTitle = preg_replace ('/^(A|The|An) /', '', $title);
$entity_field[0]['value'] = $sortTitle;
```

Once the field is re-computed for all items, I can use the contextual filter to sort 
"A book with a voice" etc under "B".

**Comment by keiserjb** [comment]
I understand now, yes glossary mode.  https://chillco.com/blog/building-glossary-filter-views

**Comment by argiepiano** [comment]
Hi @leeksoup and @keiserjb.

I've submitted a PR against your repo that adds a contextual filter for node's Natural Title. After applying the patch:

1. Create a Node view with at least the title
2. Add a Contextual Filter. Select "Title - Natural"
3. If you want the Glossary functionality, select More and select Glossary mode
4. Be sure to select at least "1" in Character limit
5. Visit the view, and add a single letter at the end of the URL

<img width="550" alt="Screen Shot 2023-04-21 at 6 10 21 PM" src="https://user-images.githubusercontent.com/9938978/233751321-478010a5-5a4d-4682-9c05-2ca5eb88dd9c.png">
<img width="570" alt="Screen Shot 2023-04-21 at 6 10 10 PM" src="https://user-images.githubusercontent.com/9938978/233751323-b8719bcd-8e6d-48e1-9d50-9f153cba05d7.png">

For example, adding "q" at the end of the query shows the title "A question" (the A is ignored)

<img width="493" alt="Screen Shot 2023-04-21 at 6 14 30 PM" src="https://user-images.githubusercontent.com/9938978/233751361-c7351b9e-3fd4-4b0f-aee0-4a99b96f8033.png">

**Comment by keiserjb** [comment]
@argiepiano Oh this is great.  I suspected the table in the database could be used.  Seems to work well.   Thank you!

**Comment by argiepiano** [comment]
Great! If this works for you, you may want to merge it. I also suggest you do an alpha release to encourage more people to test it.

**Comment by keiserjb** [comment]
I will merge it.  There is still the other issue with the days of the week that I found.  I'm using the module on at least one site.

**Comment by argiepiano** [comment]
Thanks. I also noticed issues with the fields functionality as reported in #9. That shouldn't be hard to fix.

**Comment by keiserjb** [comment]
I was working through it.  Anything you could add would be helpful.  I'll get to meet Allan, the Drupal maintainer, in person next week at MidCamp.

**Comment by leeksoup** [comment]
> Hi @leeksoup and @keiserjb.
> 
> I've submitted a PR against your repo that adds a contextual filter for node's Natural Title.

Thanks, @argiepiano! 

ETA: Just pulled the latest and tested it on my site. Works perfect!
